/**
 * Auto-generated Horizon Worlds world manager.
 * World: Simple Export Demo
 * Description: A minimal world for testing engine exports
 * Generated by OmniWorld Builder
 */

import { Component, Entity, World, PropTypes, Player } from 'horizon/core';
import { EntityFactory } from './EntityFactory';
import { EnvironmentController } from './EnvironmentController';
import { WorldData } from '../data/worldData';

/**
 * Main world manager component that orchestrates world building.
 */
class WorldManager extends Component {
  static propsDefinition = {
    autoLoad: { type: PropTypes.Boolean, default: true },
  };

  private entityFactory: EntityFactory;
  private environmentController: EnvironmentController;
  private spawnedEntities: Entity[] = [];

  constructor() {
    super();
    this.entityFactory = new EntityFactory();
    this.environmentController = new EnvironmentController();
  }

  start(): void {
    console.log(`Initializing world: ${WorldData.metadata.title}`);

    if (this.props.autoLoad) {
      this.loadWorld();
    }
  }

  /**
   * Load and build the complete world.
   */
  async loadWorld(): Promise<void> {
    console.log('Loading world...');

    // Setup environment
    await this.environmentController.setup();

    // Spawn all entities
    this.spawnedEntities = await this.entityFactory.spawnAll();

    console.log(`World loaded! Spawned ${this.spawnedEntities.length} entities`);
  }

  /**
   * Unload and clear the world.
   */
  unloadWorld(): void {
    console.log('Unloading world...');

    for (const entity of this.spawnedEntities) {
      entity.destroy();
    }
    this.spawnedEntities = [];

    console.log('World unloaded');
  }

  /**
   * Get all spawned entities.
   */
  getEntities(): Entity[] {
    return [...this.spawnedEntities];
  }

  /**
   * Find entity by name.
   */
  findEntityByName(name: string): Entity | undefined {
    return this.spawnedEntities.find(e => e.name.get() === name);
  }
}

Component.register(WorldManager);
export { WorldManager };