using UnityEngine;
using System.Collections.Generic;

namespace OmniWorld.Generated
{
    /// <summary>
    /// Auto-generated world loader for: Simple Export Demo
    /// Description: A minimal world for testing engine exports
    /// Generated by OmniWorld Builder
    /// </summary>
    public class WorldLoader : MonoBehaviour
    {
        [Header("World Settings")]
        public string worldTitle = "Simple Export Demo";
        public string worldVersion = "1.0.0";

        [Header("References")]
        public EntitySpawner entitySpawner;
        public EnvironmentController environmentController;

        private void Start()
        {
            LoadWorld();
        }

        public void LoadWorld()
        {
            Debug.Log($"Loading world: {worldTitle} v{worldVersion}");

            // Initialize environment
            if (environmentController != null)
            {
                environmentController.Initialize();
            }

            // Spawn entities
            if (entitySpawner != null)
            {
                entitySpawner.SpawnAll();
            }

            Debug.Log("World loaded successfully!");
        }

        public void UnloadWorld()
        {
            if (entitySpawner != null)
            {
                entitySpawner.DestroyAll();
            }
        }
    }
}