"""Unreal Engine Python code generator for WDL worlds."""

from pathlib import Path
from textwrap import dedent

from omniworld_builder.adapters.base import BaseAdapter
from omniworld_builder.core.wdl_schema import (
    Lighting,
    WDLEntity,
    WDLWorld,
)


class UnrealGenerator(BaseAdapter):
    """Generator for Unreal Engine Python scripts from WDL worlds."""

    def __init__(self, output_dir: str | Path = "unreal_output") -> None:
        """Initialize the Unreal generator."""
        super().__init__(output_dir)

    @property
    def platform_name(self) -> str:
        """Get the platform name."""
        return "unreal"

    @property
    def file_extension(self) -> str:
        """Get the file extension."""
        return ".py"

    def generate(self, world: WDLWorld) -> dict[str, str]:
        """Generate Unreal Python code from a WDL world.

        Args:
            world: The WDL world to generate code for.

        Returns:
            Dictionary mapping file paths to Python code content.
        """
        files: dict[str, str] = {}

        # Generate main world builder script
        files["Scripts/world_builder.py"] = self._generate_world_builder(world)

        # Generate entity definitions
        files["Scripts/entity_definitions.py"] = self._generate_entity_definitions(world)

        # Generate environment setup
        files["Scripts/environment_setup.py"] = self._generate_environment_setup(world)

        # Generate lighting setup
        files["Scripts/lighting_setup.py"] = self._generate_lighting_setup(world)

        # Generate JSON data file
        files["Data/world_data.json"] = world.to_json()

        return files

    def _generate_world_builder(self, world: WDLWorld) -> str:
        """Generate the main world builder script."""
        return dedent(f'''
            """
            Auto-generated Unreal Engine world builder script.
            World: {world.metadata.title}
            Description: {world.metadata.description}
            Generated by OmniWorld Builder
            """

            import unreal
            from entity_definitions import ENTITY_DATA, spawn_entities
            from environment_setup import setup_environment
            from lighting_setup import setup_lighting


            class WorldBuilder:
                """Builds the generated world in Unreal Engine."""

                def __init__(self):
                    self.world_title = "{world.metadata.title}"
                    self.world_version = "{world.metadata.version}"
                    self.spawned_actors = []

                def build(self):
                    """Build the complete world."""
                    unreal.log(f"Building world: {{self.world_title}} v{{self.world_version}}")

                    # Setup environment
                    setup_environment()

                    # Setup lighting
                    setup_lighting()

                    # Spawn entities
                    self.spawned_actors = spawn_entities()

                    unreal.log(f"World built successfully! Spawned {{len(self.spawned_actors)}} actors")
                    return self.spawned_actors

                def clear(self):
                    """Clear all spawned actors."""
                    for actor in self.spawned_actors:
                        if actor.is_valid():
                            actor.destroy_actor()
                    self.spawned_actors.clear()
                    unreal.log("World cleared")


            def build_world():
                """Entry point for building the world."""
                builder = WorldBuilder()
                return builder.build()


            def clear_world():
                """Entry point for clearing the world."""
                # Note: This requires tracking spawned actors
                unreal.log("Clear world called - manual cleanup may be required")


            if __name__ == "__main__":
                build_world()
        ''').strip()

    def _generate_entity_definitions(self, world: WDLWorld) -> str:
        """Generate entity definitions script."""
        entity_entries = []
        for entity in world.entities:
            entry = self._format_entity_entry(entity)
            entity_entries.append(entry)

        entities_str = ",\n    ".join(entity_entries) if entity_entries else ""

        return dedent(f'''
            """
            Entity definitions for the generated world.
            Total entities: {len(world.entities)}
            """

            import unreal
            from dataclasses import dataclass
            from typing import List, Optional


            @dataclass
            class EntityData:
                """Data class for entity information."""
                id: str
                name: str
                entity_type: str
                position: tuple
                rotation: tuple
                scale: tuple
                tags: List[str]
                asset_reference: Optional[str] = None


            ENTITY_DATA: List[EntityData] = [
                {entities_str}
            ]


            def get_actor_class(entity_type: str):
                """Get the appropriate Unreal actor class for an entity type."""
                type_mapping = {{
                    "static_mesh": unreal.StaticMeshActor,
                    "dynamic_object": unreal.Actor,
                    "character": unreal.Character,
                    "light": unreal.PointLight,
                    "camera": unreal.CameraActor,
                    "terrain": unreal.Landscape,
                    "trigger": unreal.TriggerBox,
                    "spawn_point": unreal.PlayerStart,
                }}
                return type_mapping.get(entity_type, unreal.Actor)


            def spawn_entity(data: EntityData) -> unreal.Actor:
                """Spawn a single entity in the world."""
                actor_class = get_actor_class(data.entity_type)

                # Create spawn location
                location = unreal.Vector(data.position[0], data.position[1], data.position[2])
                rotation = unreal.Rotator(data.rotation[0], data.rotation[1], data.rotation[2])

                # Spawn the actor
                spawn_params = unreal.SpawnActorParameters()
                actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
                    actor_class,
                    location,
                    rotation
                )

                if actor:
                    # Set name and scale
                    actor.set_actor_label(data.name)
                    actor.set_actor_scale3d(unreal.Vector(data.scale[0], data.scale[1], data.scale[2]))

                    # Add tags
                    for tag in data.tags:
                        actor.tags.append(tag)

                return actor


            def spawn_entities() -> List[unreal.Actor]:
                """Spawn all entities defined in ENTITY_DATA."""
                spawned = []
                for data in ENTITY_DATA:
                    actor = spawn_entity(data)
                    if actor:
                        spawned.append(actor)
                        unreal.log(f"Spawned: {{data.name}}")
                    else:
                        unreal.log_warning(f"Failed to spawn: {{data.name}}")
                return spawned
        ''').strip()

    def _format_entity_entry(self, entity: WDLEntity) -> str:
        """Format a single entity as Python initialization code."""
        pos = entity.transform.position
        rot = entity.transform.rotation
        scale = entity.transform.scale
        tags = ", ".join(f'"{t}"' for t in entity.tags) if entity.tags else ""
        asset_ref = f'"{entity.asset_reference}"' if entity.asset_reference else "None"

        return f'''EntityData(
            id="{entity.id}",
            name="{entity.name}",
            entity_type="{entity.entity_type.value}",
            position=({pos.x}, {pos.y}, {pos.z}),
            rotation=({rot.x}, {rot.y}, {rot.z}),
            scale=({scale.x}, {scale.y}, {scale.z}),
            tags=[{tags}],
            asset_reference={asset_ref}
        )'''

    def _generate_environment_setup(self, world: WDLWorld) -> str:
        """Generate environment setup script."""
        env = world.environment
        ambient = env.ambient_light
        fog = env.fog_color
        gravity = env.gravity

        return dedent(f'''
            """
            Environment setup for the generated world.
            """

            import unreal


            # Environment configuration
            ENVIRONMENT_CONFIG = {{
                "weather": "{env.weather.value}",
                "time_hour": {env.time_of_day.hour},
                "time_minute": {env.time_of_day.minute},
                "day_night_cycle": {env.time_of_day.day_night_cycle},
                "ambient_color": ({ambient.r}, {ambient.g}, {ambient.b}),
                "fog_enabled": {env.fog_enabled},
                "fog_color": ({fog.r}, {fog.g}, {fog.b}),
                "fog_density": {env.fog_density},
                "gravity": ({gravity.x}, {gravity.y}, {gravity.z}),
                "skybox_type": "{env.skybox.skybox_type}",
            }}


            def setup_environment():
                """Configure the world environment settings."""
                unreal.log("Setting up environment...")

                # Get world settings
                world = unreal.EditorLevelLibrary.get_editor_world()
                if not world:
                    unreal.log_error("No world found!")
                    return

                # Setup fog
                if ENVIRONMENT_CONFIG["fog_enabled"]:
                    setup_fog()

                # Setup sky
                setup_sky()

                unreal.log("Environment setup complete")


            def setup_fog():
                """Configure exponential height fog."""
                fog_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
                    unreal.ExponentialHeightFog,
                    unreal.Vector(0, 0, 0)
                )

                if fog_actor:
                    fog_component = fog_actor.get_component_by_class(unreal.ExponentialHeightFogComponent)
                    if fog_component:
                        fog_color = ENVIRONMENT_CONFIG["fog_color"]
                        fog_component.set_fog_inscattering_color(
                            unreal.LinearColor(fog_color[0], fog_color[1], fog_color[2])
                        )
                        fog_component.set_fog_density(ENVIRONMENT_CONFIG["fog_density"])


            def setup_sky():
                """Configure sky atmosphere and clouds."""
                # Spawn sky atmosphere
                sky_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
                    unreal.SkyAtmosphere,
                    unreal.Vector(0, 0, 0)
                )

                if sky_actor:
                    unreal.log("Sky atmosphere created")

                # Spawn sky light
                sky_light = unreal.EditorLevelLibrary.spawn_actor_from_class(
                    unreal.SkyLight,
                    unreal.Vector(0, 0, 100)
                )

                if sky_light:
                    sky_light_component = sky_light.get_component_by_class(unreal.SkyLightComponent)
                    if sky_light_component:
                        ambient = ENVIRONMENT_CONFIG["ambient_color"]
                        sky_light_component.set_intensity(1.0)
        ''').strip()

    def _generate_lighting_setup(self, world: WDLWorld) -> str:
        """Generate lighting setup script."""
        light_entries = []
        for light in world.lights:
            entry = self._format_light_entry(light)
            light_entries.append(entry)

        lights_str = ",\n    ".join(light_entries) if light_entries else ""

        return dedent(f'''
            """
            Lighting setup for the generated world.
            Total lights: {len(world.lights)}
            """

            import unreal
            from dataclasses import dataclass
            from typing import List


            @dataclass
            class LightData:
                """Data class for light information."""
                name: str
                light_type: str
                color: tuple
                intensity: float
                position: tuple
                rotation: tuple
                cast_shadows: bool


            LIGHT_DATA: List[LightData] = [
                {lights_str}
            ]


            def get_light_class(light_type: str):
                """Get the appropriate Unreal light class."""
                type_mapping = {{
                    "directional": unreal.DirectionalLight,
                    "point": unreal.PointLight,
                    "spot": unreal.SpotLight,
                    "area": unreal.RectLight,
                }}
                return type_mapping.get(light_type, unreal.PointLight)


            def spawn_light(data: LightData) -> unreal.Actor:
                """Spawn a single light in the world."""
                light_class = get_light_class(data.light_type)

                location = unreal.Vector(data.position[0], data.position[1], data.position[2])
                rotation = unreal.Rotator(data.rotation[0], data.rotation[1], data.rotation[2])

                light_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
                    light_class,
                    location,
                    rotation
                )

                if light_actor:
                    light_actor.set_actor_label(data.name)

                    # Configure light component
                    light_component = light_actor.get_component_by_class(unreal.LightComponent)
                    if light_component:
                        light_component.set_intensity(data.intensity)
                        light_component.set_light_color(
                            unreal.LinearColor(data.color[0], data.color[1], data.color[2])
                        )
                        light_component.set_cast_shadows(data.cast_shadows)

                return light_actor


            def setup_lighting() -> List[unreal.Actor]:
                """Setup all lights defined in LIGHT_DATA."""
                unreal.log("Setting up lighting...")
                lights = []

                for data in LIGHT_DATA:
                    light = spawn_light(data)
                    if light:
                        lights.append(light)
                        unreal.log(f"Created light: {{data.name}}")

                unreal.log(f"Lighting setup complete: {{len(lights)}} lights created")
                return lights
        ''').strip()

    def _format_light_entry(self, light: Lighting) -> str:
        """Format a single light as Python initialization code."""
        pos = light.transform.position
        rot = light.transform.rotation

        return f'''LightData(
            name="{light.name}",
            light_type="{light.light_type.value}",
            color=({light.color.r}, {light.color.g}, {light.color.b}),
            intensity={light.intensity},
            position=({pos.x}, {pos.y}, {pos.z}),
            rotation=({rot.x}, {rot.y}, {rot.z}),
            cast_shadows={light.cast_shadows}
        )'''
