"""Unity C# code generator for WDL worlds."""

from pathlib import Path
from textwrap import dedent

from omniworld_builder.adapters.base import BaseAdapter
from omniworld_builder.core.wdl_schema import (
    Lighting,
    LightType,
    WDLEntity,
    WDLWorld,
)


class UnityGenerator(BaseAdapter):
    """Generator for Unity C# scripts from WDL worlds."""

    def __init__(self, output_dir: str | Path = "unity_output") -> None:
        """Initialize the Unity generator."""
        super().__init__(output_dir)

    @property
    def platform_name(self) -> str:
        """Get the platform name."""
        return "unity"

    @property
    def file_extension(self) -> str:
        """Get the file extension."""
        return ".cs"

    def generate(self, world: WDLWorld) -> dict[str, str]:
        """Generate Unity C# code from a WDL world.

        Args:
            world: The WDL world to generate code for.

        Returns:
            Dictionary mapping file paths to C# code content.
        """
        files: dict[str, str] = {}

        # Generate main world loader script
        files["Scripts/WorldLoader.cs"] = self._generate_world_loader(world)

        # Generate entity spawner
        files["Scripts/EntitySpawner.cs"] = self._generate_entity_spawner(world)

        # Generate environment controller
        files["Scripts/EnvironmentController.cs"] = self._generate_environment_controller(world)

        # Generate world data scriptable object
        files["Scripts/WorldData.cs"] = self._generate_world_data(world)

        # Generate JSON data file
        files["Data/world_data.json"] = world.to_json()

        return files

    def _generate_world_loader(self, world: WDLWorld) -> str:
        """Generate the main world loader script."""
        return dedent(f'''
            using UnityEngine;
            using System.Collections.Generic;

            namespace OmniWorld.Generated
            {{
                /// <summary>
                /// Auto-generated world loader for: {world.metadata.title}
                /// Description: {world.metadata.description}
                /// Generated by OmniWorld Builder
                /// </summary>
                public class WorldLoader : MonoBehaviour
                {{
                    [Header("World Settings")]
                    public string worldTitle = "{world.metadata.title}";
                    public string worldVersion = "{world.metadata.version}";

                    [Header("References")]
                    public EntitySpawner entitySpawner;
                    public EnvironmentController environmentController;

                    private void Start()
                    {{
                        LoadWorld();
                    }}

                    public void LoadWorld()
                    {{
                        Debug.Log($"Loading world: {{worldTitle}} v{{worldVersion}}");

                        // Initialize environment
                        if (environmentController != null)
                        {{
                            environmentController.Initialize();
                        }}

                        // Spawn entities
                        if (entitySpawner != null)
                        {{
                            entitySpawner.SpawnAll();
                        }}

                        Debug.Log("World loaded successfully!");
                    }}

                    public void UnloadWorld()
                    {{
                        if (entitySpawner != null)
                        {{
                            entitySpawner.DestroyAll();
                        }}
                    }}
                }}
            }}
        ''').strip()

    def _generate_entity_spawner(self, world: WDLWorld) -> str:
        """Generate the entity spawner script."""
        entity_entries = []
        for entity in world.entities:
            entry = self._format_entity_entry(entity)
            entity_entries.append(entry)

        entities_init = ",\n            ".join(entity_entries) if entity_entries else ""

        return dedent(f'''
            using UnityEngine;
            using System.Collections.Generic;

            namespace OmniWorld.Generated
            {{
                [System.Serializable]
                public class EntityData
                {{
                    public string id;
                    public string name;
                    public string entityType;
                    public Vector3 position;
                    public Vector3 rotation;
                    public Vector3 scale;
                    public string[] tags;
                    public string assetReference;
                }}

                /// <summary>
                /// Spawns entities for the generated world.
                /// Total entities: {len(world.entities)}
                /// </summary>
                public class EntitySpawner : MonoBehaviour
                {{
                    [Header("Entity Prefabs")]
                    public GameObject defaultPrefab;
                    public Dictionary<string, GameObject> prefabLookup = new Dictionary<string, GameObject>();

                    private List<GameObject> spawnedEntities = new List<GameObject>();

                    private EntityData[] entityDataList = new EntityData[]
                    {{
                        {entities_init}
                    }};

                    public void SpawnAll()
                    {{
                        foreach (var data in entityDataList)
                        {{
                            SpawnEntity(data);
                        }}
                        Debug.Log($"Spawned {{entityDataList.Length}} entities");
                    }}

                    public GameObject SpawnEntity(EntityData data)
                    {{
                        GameObject prefab = defaultPrefab;
                        if (!string.IsNullOrEmpty(data.assetReference) && prefabLookup.ContainsKey(data.assetReference))
                        {{
                            prefab = prefabLookup[data.assetReference];
                        }}

                        if (prefab == null)
                        {{
                            // Create primitive as fallback
                            prefab = GameObject.CreatePrimitive(GetPrimitiveType(data.entityType));
                        }}

                        GameObject instance = Instantiate(prefab, data.position, Quaternion.Euler(data.rotation));
                        instance.name = data.name;
                        instance.transform.localScale = data.scale;

                        spawnedEntities.Add(instance);
                        return instance;
                    }}

                    public void DestroyAll()
                    {{
                        foreach (var entity in spawnedEntities)
                        {{
                            if (entity != null)
                            {{
                                Destroy(entity);
                            }}
                        }}
                        spawnedEntities.Clear();
                    }}

                    private PrimitiveType GetPrimitiveType(string entityType)
                    {{
                        return entityType switch
                        {{
                            "terrain" => PrimitiveType.Plane,
                            "light" => PrimitiveType.Sphere,
                            _ => PrimitiveType.Cube
                        }};
                    }}
                }}
            }}
        ''').strip()

    def _format_entity_entry(self, entity: WDLEntity) -> str:
        """Format a single entity as C# initialization code."""
        pos = entity.transform.position
        rot = entity.transform.rotation
        scale = entity.transform.scale
        tags = ", ".join(f'"{t}"' for t in entity.tags) if entity.tags else ""
        asset_ref = entity.asset_reference or ""

        return f'''new EntityData {{
                    id = "{entity.id}",
                    name = "{entity.name}",
                    entityType = "{entity.entity_type.value}",
                    position = new Vector3({pos.x}f, {pos.y}f, {pos.z}f),
                    rotation = new Vector3({rot.x}f, {rot.y}f, {rot.z}f),
                    scale = new Vector3({scale.x}f, {scale.y}f, {scale.z}f),
                    tags = new string[] {{ {tags} }},
                    assetReference = "{asset_ref}"
                }}'''

    def _generate_environment_controller(self, world: WDLWorld) -> str:
        """Generate the environment controller script."""
        env = world.environment
        ambient = env.ambient_light

        light_entries = []
        for light in world.lights:
            entry = self._format_light_entry(light)
            light_entries.append(entry)

        lights_init = ",\n            ".join(light_entries) if light_entries else ""

        return dedent(f'''
            using UnityEngine;
            using System.Collections.Generic;

            namespace OmniWorld.Generated
            {{
                [System.Serializable]
                public class LightData
                {{
                    public string name;
                    public LightType lightType;
                    public Color color;
                    public float intensity;
                    public Vector3 position;
                    public Vector3 rotation;
                    public bool castShadows;
                }}

                /// <summary>
                /// Controls environment settings for the generated world.
                /// </summary>
                public class EnvironmentController : MonoBehaviour
                {{
                    [Header("Environment Settings")]
                    public Color ambientColor = new Color({ambient.r}f, {ambient.g}f, {ambient.b}f, {ambient.a}f);
                    public bool fogEnabled = {str(env.fog_enabled).lower()};
                    public Color fogColor = new Color({env.fog_color.r}f, {env.fog_color.g}f, {env.fog_color.b}f);
                    public float fogDensity = {env.fog_density}f;

                    [Header("Time Settings")]
                    public int timeHour = {env.time_of_day.hour};
                    public int timeMinute = {env.time_of_day.minute};
                    public bool dayNightCycle = {str(env.time_of_day.day_night_cycle).lower()};

                    private List<Light> createdLights = new List<Light>();

                    private LightData[] lightDataList = new LightData[]
                    {{
                        {lights_init}
                    }};

                    public void Initialize()
                    {{
                        SetupAmbient();
                        SetupFog();
                        CreateLights();
                    }}

                    private void SetupAmbient()
                    {{
                        RenderSettings.ambientLight = ambientColor;
                        RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
                    }}

                    private void SetupFog()
                    {{
                        RenderSettings.fog = fogEnabled;
                        RenderSettings.fogColor = fogColor;
                        RenderSettings.fogDensity = fogDensity;
                        RenderSettings.fogMode = FogMode.Exponential;
                    }}

                    private void CreateLights()
                    {{
                        foreach (var data in lightDataList)
                        {{
                            CreateLight(data);
                        }}
                        Debug.Log($"Created {{lightDataList.Length}} lights");
                    }}

                    private void CreateLight(LightData data)
                    {{
                        GameObject lightObj = new GameObject(data.name);
                        lightObj.transform.position = data.position;
                        lightObj.transform.rotation = Quaternion.Euler(data.rotation);
                        lightObj.transform.SetParent(transform);

                        Light light = lightObj.AddComponent<Light>();
                        light.type = data.lightType;
                        light.color = data.color;
                        light.intensity = data.intensity;
                        light.shadows = data.castShadows ? LightShadows.Soft : LightShadows.None;

                        createdLights.Add(light);
                    }}
                }}
            }}
        ''').strip()

    def _format_light_entry(self, light: Lighting) -> str:
        """Format a single light as C# initialization code."""
        pos = light.transform.position
        rot = light.transform.rotation
        unity_light_type = self._get_unity_light_type(light.light_type)

        return f'''new LightData {{
                    name = "{light.name}",
                    lightType = LightType.{unity_light_type},
                    color = new Color({light.color.r}f, {light.color.g}f, {light.color.b}f),
                    intensity = {light.intensity}f,
                    position = new Vector3({pos.x}f, {pos.y}f, {pos.z}f),
                    rotation = new Vector3({rot.x}f, {rot.y}f, {rot.z}f),
                    castShadows = {str(light.cast_shadows).lower()}
                }}'''

    def _get_unity_light_type(self, light_type: LightType) -> str:
        """Convert WDL light type to Unity LightType."""
        mapping = {
            LightType.DIRECTIONAL: "Directional",
            LightType.POINT: "Point",
            LightType.SPOT: "Spot",
            LightType.AREA: "Area",
            LightType.AMBIENT: "Point",  # Unity doesn't have ambient light type
        }
        return mapping.get(light_type, "Point")

    def _generate_world_data(self, world: WDLWorld) -> str:
        """Generate the world data scriptable object."""
        return dedent(f'''
            using UnityEngine;

            namespace OmniWorld.Generated
            {{
                /// <summary>
                /// Scriptable object containing world metadata.
                /// </summary>
                [CreateAssetMenu(fileName = "WorldData", menuName = "OmniWorld/World Data")]
                public class WorldData : ScriptableObject
                {{
                    [Header("Metadata")]
                    public string worldTitle = "{world.metadata.title}";
                    public string description = "{world.metadata.description}";
                    public string author = "{world.metadata.author}";
                    public string version = "{world.metadata.version}";

                    [Header("Bounds")]
                    public Vector3 minBounds = new Vector3({world.bounds.min_bounds.x}f, {world.bounds.min_bounds.y}f, {world.bounds.min_bounds.z}f);
                    public Vector3 maxBounds = new Vector3({world.bounds.max_bounds.x}f, {world.bounds.max_bounds.y}f, {world.bounds.max_bounds.z}f);

                    [Header("Statistics")]
                    public int entityCount = {len(world.entities)};
                    public int lightCount = {len(world.lights)};
                    public int systemCount = {len(world.systems)};
                }}
            }}
        ''').strip()
