"""
Auto-generated Unreal Engine world builder script.
World: Simple Export Demo
Description: A minimal world for testing engine exports
Generated by OmniWorld Builder
"""

import unreal
from entity_definitions import ENTITY_DATA, spawn_entities
from environment_setup import setup_environment
from lighting_setup import setup_lighting


class WorldBuilder:
    """Builds the generated world in Unreal Engine."""

    def __init__(self):
        self.world_title = "Simple Export Demo"
        self.world_version = "1.0.0"
        self.spawned_actors = []

    def build(self):
        """Build the complete world."""
        unreal.log(f"Building world: {self.world_title} v{self.world_version}")

        # Setup environment
        setup_environment()

        # Setup lighting
        setup_lighting()

        # Spawn entities
        self.spawned_actors = spawn_entities()

        unreal.log(f"World built successfully! Spawned {len(self.spawned_actors)} actors")
        return self.spawned_actors

    def clear(self):
        """Clear all spawned actors."""
        for actor in self.spawned_actors:
            if actor.is_valid():
                actor.destroy_actor()
        self.spawned_actors.clear()
        unreal.log("World cleared")


def build_world():
    """Entry point for building the world."""
    builder = WorldBuilder()
    return builder.build()


def clear_world():
    """Entry point for clearing the world."""
    # Note: This requires tracking spawned actors
    unreal.log("Clear world called - manual cleanup may be required")


if __name__ == "__main__":
    build_world()