/**
 * World data for: Simple Export Demo
 * Generated by OmniWorld Builder
 */

import { WorldMetadata } from '../scripts/types';

/**
 * World metadata.
 */
export const WorldData = {
  metadata: {
    title: "Simple Export Demo",
    description: "A minimal world for testing engine exports",
    author: "OmniWorld Builder",
    version: "1.0.0",
    tags: [],
    targetPlatforms: ["unity", "unreal", "horizon"],
  } as WorldMetadata,

  bounds: {
    min: { x: -1000.0, y: -100.0, z: -1000.0 },
    max: { x: 1000.0, y: 500.0, z: 1000.0 },
  },

  statistics: {
    entityCount: 3,
    lightCount: 2,
    systemCount: 0,
  },
};